#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Project Euler Problem $problem
=======================

$problem_text
"""

def problem$problem():
    pass

def main():
    print(problem$problem())

main()



